require 'yaml'

config_path = File.expand_path("../../config.yaml", __FILE__)
config_vars = YAML.load_file(config_path)

Vagrant.configure("2") do |config|

    (0..1).each do |i|
        config.vm.define "worker-#{i+1}" do |node|
            node.vm.box = "ubuntu/focal64"
            node.vm.hostname = config_vars["worker_names"][i]

            node.vm.network "public_network", 
              bridge: config_vars["host_adapter"],
              ip: config_vars["worker_ips"][i], 
              netmask: config_vars["worker_netmask"],
              hostname: true
        
            node.vm.provider "virtualbox" do |vb|
              vb.name = config_vars["worker_names"][i]
              vb.memory = config_vars["worker_ram"] 
              vb.cpus = config_vars["worker_cpus"]        
            end
        
            node.vm.provision "file", source: config_vars["host_ssh_pubkey"], destination: "~/.ssh/id_rsa.pub"

            node.vm.provision "shell", inline: <<-SHELL
            sudo useradd -m -s /bin/bash -G sudo user
            echo "user:user" | sudo chpasswd

            echo "user ALL=(ALL) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/user
        
            # Enable SSH for the user by copying the SSH keys from the vagrant user
            sudo mkdir -p /home/user/.ssh
            sudo cat /home/vagrant/.ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys 
            sudo cp /home/vagrant/.ssh/authorized_keys /home/user/.ssh/ 

            # Set the ownership and permissions for the user
            sudo chown -R user:user /home/user/.ssh
            sudo chmod 700 /home/user/.ssh
            sudo chmod 600 /home/user/.ssh/authorized_keys

            # Lock the root account for better security (optional)
            #sudo passwd -l root
            SHELL

            # Configure default nameserver
            node.vm.provision "shell", inline: <<-SHELL
            sudo sed -i 's/^#*DNS=/DNS=8.8.8.8/' /etc/systemd/resolved.conf
            sudo systemctl restart systemd-resolved
            SHELL
        end
    end
end