- hosts: k8s_masters
  name: Retrieve join token
  tasks:
    - shell: 
        cmd: kubeadm token create --print-join-command
      register: token_cmd_output
      become: yes
    - name: Store join command in dummy host
      add_host:
        name: "K8S_JOIN_CMD_HOLDER"
        cmd: "{{ token_cmd_output.stdout_lines[0] }}"

- hosts: k8s_workers
  name: Join workers to the cluster
  become: yes
  tasks:
    #- debug:
    #    var: hostvars.K8S_JOIN_CMD_HOLDER.cmd
    - name: Replace control plane IP in join command
      set_fact:
        MODIFIED_JOIN_COMMAND: "{{ hostvars.K8S_JOIN_CMD_HOLDER.cmd | regex_replace('([0-9]{1,3}(\\.[0-9]{1,3}){3})', master_ip) }}"
    - debug:
        msg: "The join command: {{ MODIFIED_JOIN_COMMAND }}"
    - shell: 
        cmd: kubeadm reset -f
    - name: Run join command
      shell:    
        cmd: "{{ MODIFIED_JOIN_COMMAND }} --node-name={{ node_name }}" 