master_name: "local-k8s-master"
worker_names:
  - "local-k8s-vworker1"
  - "local-k8s-vworker2"
master_ip: "192.168.0.2"
master_netmask: "255.255.255.0"
worker_ips:
  - "192.168.0.3"
  - "192.168.0.4"
worker_netmask: "255.255.255.0"
master_cpus: 2
worker_cpus: 2
master_ram: 2048
worker_ram: 2048

# You should change those
host_adapter: "wlp0s20f3"
host_ssh_pubkey: "~/.ssh/id_rsa.pub"